development:
  adapter: postgresql
  encoding: unicode
  database: RailsProject_development
  pool: 5
  username: timebomb2788
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: RailsProject_test
  pool: 5
  username: timebomb2788
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: RailsProject_production
  pool: 5
  username: timebomb2788
  password:
